services:
  db:
    image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - database:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=thisisunsafe
      - MYSQL_DATABASE=demosite_db
      - MYSQL_USER=demosite_usr
      - MYSQL_PASSWORD=demosite_pwd
    expose:
      - 3306
  wordpress:
    image: wordpress:latest
    volumes:
      - wordpress:/var/www/html
    ports:
      - 8888:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=demosite_usr
      - WORDPRESS_DB_PASSWORD=demosite_pwd
      - WORDPRESS_DB_NAME=demosite_db
volumes:
  database:
  wordpress:
